name: Go-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Run go vet
        run: go vet ./...

